import type {Metadata} from "next";
import "./globals.css";
import {AuthProvider} from "@/features/auth/providers/authProvider";
import {NotificationProvider} from "@/components/ui/alert";
import TanstackProvider from "@/components/providers/tanstack-query/TanstackProvider";

export const metadata: Metadata = {
  title: "Morena Gowns and Barongs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased font-[Arial,sans-serif]">
        <NotificationProvider>
          <TanstackProvider>
            <AuthProvider>{children}</AuthProvider>
          </TanstackProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}
