import type {Metadata} from "next";
import "./globals.css";
import {AuthProvider} from "@/features/auth/providers/authProvider";
import {NotificationProvider} from "@/components/ui/alert";

export const metadata: Metadata = {
  title: "Morena Gowns and Barongs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased font-[Arial,sans-serif]">
        <NotificationProvider>
          <AuthProvider>{children}</AuthProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}
