import type {Types} from "mongoose";
import type {Snapshot} from "./ISnapshot.js";

export type OrderStatus = "pending" | "received" | "cancelled";

export interface IOrder {
  _id?: Types.ObjectId;
  referenceID?: string; // auto-generated by the OrderModel "validate" pre-hook
  userID: Types.ObjectId;

  type: "purchase";

  items: Snapshot[];
  isPackage: boolean;

  totalAmount: number;

  status: OrderStatus;

  paymentID?: Types.ObjectId;

  createdAt?: Date;
  updatedAt?: Date;
}